### ISSUE TITLE
プロジェクト申請画面作成

### ISSUE THREAD

**Issue by coelacanth0715** [selelab/admin#11]
## 申請時に必要な情報
- プロジェクト名
- プロジェクト概要
- 会計種別
- 予算上限額

~~プロジェクト一覧のリストからプロジェクトの詳細を開いたときにも予算上限が見えるようにしてほしい~~
2020/03/21追記 `kusatsu` の話だったので `ネオ` の話になるようにタイトルや説明を変更しました。

**Comment by Tsutomu-Ikeda** [comment]
## 概要
同様の意味を持つ `承認額` という項目は作ってあります

## 今後決めること
ここの文言を `予算上限額` にするかは話し合いが必要

![image](https://user-images.githubusercontent.com/40418321/77142246-d9e3b500-6ac2-11ea-93f6-f6e725dc5830.png)

**Comment by coelacanth0715** [comment]
確か会則には「予算上限」とあるのでややこしくならないように「予算上限」という単語のほうがいいかと…

**Comment by Tsutomu-Ikeda** [comment]
予算上限に文言を統一 8fc0938d9e79bca61c003a14afa0f99b6bf8ed66

![image](https://user-images.githubusercontent.com/40418321/77228490-2a463a00-6bcb-11ea-9f12-f7deb1a52fb8.png)
![image](https://user-images.githubusercontent.com/40418321/77228501-33370b80-6bcb-11ea-884b-b13bbded2fd7.png)
