### ISSUE TITLE
プロジェクト一覧 改善

### ISSUE THREAD

**Issue by coelacanth0715** [selelab/admin#13]
プロジェクトの担当者が誰なのか一目でわかるようにしたい

プロジェクト一覧のリストからプロジェクトの詳細を開いたときにも予算上限が見えるようにしてほしい

**Comment by coelacanth0715** [comment]
![image](https://user-images.githubusercontent.com/62389508/77141792-74db8f80-6ac1-11ea-8278-afc87a473640.png)

**Comment by Tsutomu-Ikeda** [comment]
https://selelab.com/admin/projects/
一覧では担当者のアイコンのみを表示する予定
詳細まで飛ぶと担当者の名前まで出てくるが、これがわかりやすいかはまだ検証が足りないので、今後検証を進めていく

![image](https://user-images.githubusercontent.com/40418321/77142046-4dd18d80-6ac2-11ea-853d-3b23216c6d53.png)
