### ISSUE TITLE
プロジェクト編集画面 機能拡充

### ISSUE THREAD

**Issue by coelacanth0715** [selelab/admin#14]
## 概要
プロジェクトリーダーは、自分のユーザーページにある自分のプロジェクト一覧から、各プロジェクトの管理画面に飛ぶことができるようにしてほしい。
予算申請の欄があり、そこに数字を入力し、その下にある「申請」ボタンで申請することができる。
もう一つの入力欄として、プロジェクトを完了させる「完了にする」というボタンをおく。これを押すとプロジェクトが完了する。

## プロジェクトに必要な情報
- プロジェクト名
- プロジェクト概要
- 会計種別
- 完了かどうか
- 承認済予算
- 支出済予算

## 想定されるエラー
- 予算上限の超過

## その他機能
- 申請された予算は、会計担当に送られる。
  - メールで通知など
- 支給されたらプロジェクトの支出済予算にその分が足される。

以下の雑な画像のイメージです。青枠は入力欄、赤枠はボタンのイメージ。

![image](https://user-images.githubusercontent.com/62389508/77142873-ca656b80-6ac4-11ea-8fb1-640defbf9e93.png)

**Comment by Tsutomu-Ikeda** [comment]
## 考えたことメモ

### 要約
プロジェクトの新規申請と、追加予算申請は別々にしたい。
そして、プロジェクトを立ち上げてから完了にさせるまでの設計を綿密に考える必要がある。

### 具体的な項目
#### プロジェクトの新規申請
- プロジェクト名
- プロジェクト概要
- 会計種別 ([会則18条](https://github.com/selelab/regulations/blob/master/%E4%BC%9A%E5%89%87.md#%E7%AC%AC%E5%8D%81%E5%85%AB%E6%9D%A1%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E5%8C%BA%E5%88%86) [会計細則1条](https://github.com/selelab/regulations/blob/master/%E4%BC%9A%E8%A8%88%E7%B4%B0%E5%89%87.md#%E7%AC%AC%E4%B8%80%E6%9D%A1%E5%BD%B9%E5%93%A1%E3%81%AE%E5%BD%B9%E5%89%B2))
- 予算申請額 ([会計細則5条](https://github.com/selelab/regulations/blob/master/%E4%BC%9A%E8%A8%88%E7%B4%B0%E5%89%87.md#%E7%AC%AC%E4%BA%94%E6%9D%A1%E4%BA%88%E7%AE%97%E6%A6%82%E8%A6%81%E3%81%AE%E6%8F%90%E7%A4%BA))

#### 追加予算申請/プロジェクト編集
- 通常編集
  - 超過予算の申請 ([会計細則8条](https://github.com/selelab/regulations/blob/master/%E4%BC%9A%E8%A8%88%E7%B4%B0%E5%89%87.md#%E7%AC%AC%E4%B8%80%E6%9D%A1%E5%BD%B9%E5%93%A1%E3%81%AE%E5%BD%B9%E5%89%B2))
  - プロジェクトを完了する
  - 支出予算登録
    - レシート登録する画面作りたいなあ ([会則19条](https://github.com/selelab/regulations/blob/master/%E4%BC%9A%E5%89%87.md#%E7%AC%AC%E5%8D%81%E4%B9%9D%E6%9D%A1%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E5%A0%B1%E5%91%8A%E7%BE%A9%E5%8B%99))
- 会計担当編集
  - 支出予算を承認する
  
- 管理者権限編集
  - 規則に基づく事項
    - 新規プロジェクトを承認する(総会による承認)
      - ここ、会則/会計細則の条項は見当たらなかったけどもしかしてない？ @BARISU 
  - 利便性のための事項
    - プロジェクト名
    - プロジェクト概要
    - 会計種別
    - 完了したプロジェクトを再開する

**Comment by Tsutomu-Ikeda** [comment]
申請フォームの横にクエスチョンマーク付けといて、押したら根拠会則に飛ぶとかいう機能つけたいなあ
