### ISSUE TITLE
プロジェクトの新規申請時にエラーが発生する

### ISSUE THREAD

**Issue by stepney141** [selelab/admin#37]
## 概要

ログイン状態において、プロジェクト申請画面において規定の欄に入力して「申請」ボタンを押した。
しかし申請処理が正常に終了せず、``メールアドレスまたはパスワードが正しくありません。``とのプロンプトが出現した。

入力する内容を変えて実験した結果、「プロジェクト説明」欄の入力内容によってエラーが発生するかどうかが決まるらしいこことが分かった（「プロジェクト名」「会計種別」「予算上限額」の欄はエラーの有無に影響を及ぼさなかった）。

- エラーが出た入力内容
	- https://gist.githubusercontent.com/stepney141/add27ef241026c9c60aa753bb835b2a4/raw/5f33035c5d3b5232915814d9d2c6602173f07f43/plansheet.md
- エラーが出なかった入力内容
	-「テスト」
	-「test」
	-「### 概要\n ### 予算内訳\n\n」

## 再現した環境

- Chrome 90.0.4430.82 (Android 10)
- Chrome 90.0.4430.85 (Windows 10)
- Firefox 88.0 (Windows 10)

**Comment by Tsutomu-Ikeda** [comment]
ローカルで再現したところ、

```
{description: ["Ensure this field has no more than 500 characters."]}
description: ["Ensure this field has no more than 500 characters."]
0: "Ensure this field has no more than 500 characters."
```

というエラーが出た。

![image](https://user-images.githubusercontent.com/40418321/116101225-9fe2da80-a6e8-11eb-91e5-9eb38974b11b.png)

**Comment by Tsutomu-Ikeda** [comment]
@stepney141 
ひとまずの対応として500文字以内に収めてほしいです！

**Comment by Tsutomu-Ikeda** [comment]
TODO: エラーメッセージ改修

**Comment by stepney141** [comment]
> @stepney141
> ひとまずの対応として500文字以内に収めてほしいです！

了解です！

**Comment by Tsutomu-Ikeda** [comment]
プロジェクト説明をモリモリにして9MBしたら、`413 Request Entity Too Large` エラーになるっぽい…

![image](https://user-images.githubusercontent.com/40418321/117530145-8316a300-b016-11eb-8725-dcb0e9790d46.png)

ただし、流石にここまで書くケースはないはずなので、対応は必要ないかと。

**Comment by Tsutomu-Ikeda** [comment]
@stepney141 
根本的な対応はできていないものの、ひとまずエラー表示は分かりやすくなったかと思います。
サーバー側の対応は別Issueでやりましょう！！
